//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachtAuthenticate.Translations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MachtAuthenticate.Translations.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Macht Authenticate....
        /// </summary>
        public static string MenuAboutApp {
            get {
                return ResourceManager.GetString("MenuAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always On Top.
        /// </summary>
        public static string MenuAlwaysOnTop {
            get {
                return ResourceManager.GetString("MenuAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macht Authenticate Website....
        /// </summary>
        public static string MenuAppWebsite {
            get {
                return ResourceManager.GetString("MenuAppWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language....
        /// </summary>
        public static string MenuChangeLanguage {
            get {
                return ResourceManager.GetString("MenuChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Master Key....
        /// </summary>
        public static string MenuChangeMasterKey {
            get {
                return ResourceManager.GetString("MenuChangeMasterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string MenuCheckUpdates {
            get {
                return ResourceManager.GetString("MenuCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Columns....
        /// </summary>
        public static string MenuConfigureColumns {
            get {
                return ResourceManager.GetString("MenuConfigureColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Maintenance....
        /// </summary>
        public static string MenuDatabaseMaintenance {
            get {
                return ResourceManager.GetString("MenuDatabaseMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Settings....
        /// </summary>
        public static string MenuDatabaseSettings {
            get {
                return ResourceManager.GetString("MenuDatabaseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Tools.
        /// </summary>
        public static string MenuDatabaseTools {
            get {
                return ResourceManager.GetString("MenuDatabaseTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Duplicated Entries.
        /// </summary>
        public static string MenuDeleteDuplicatedEntries {
            get {
                return ResourceManager.GetString("MenuDeleteDuplicatedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Empty Groups.
        /// </summary>
        public static string MenuDeleteEmptyGroups {
            get {
                return ResourceManager.GetString("MenuDeleteEmptyGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Unused Custom Icons.
        /// </summary>
        public static string MenuDeleteUnusedCustomIcons {
            get {
                return ResourceManager.GetString("MenuDeleteUnusedCustomIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate....
        /// </summary>
        public static string MenuDonate {
            get {
                return ResourceManager.GetString("MenuDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Entry View.
        /// </summary>
        public static string MenuEntryView {
            get {
                return ResourceManager.GetString("MenuEntryView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        public static string MenuExport {
            get {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find....
        /// </summary>
        public static string MenuFind {
            get {
                return ResourceManager.GetString("MenuFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Password....
        /// </summary>
        public static string MenuGeneratePassword {
            get {
                return ResourceManager.GetString("MenuGeneratePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Password List....
        /// </summary>
        public static string MenuGeneratePasswordList {
            get {
                return ResourceManager.GetString("MenuGeneratePasswordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping in Entry List.
        /// </summary>
        public static string MenuGroupingInEntryList {
            get {
                return ResourceManager.GetString("MenuGroupingInEntryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Contents.
        /// </summary>
        public static string MenuHelpContents {
            get {
                return ResourceManager.GetString("MenuHelpContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Source....
        /// </summary>
        public static string MenuHelpSource {
            get {
                return ResourceManager.GetString("MenuHelpSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import....
        /// </summary>
        public static string MenuImport {
            get {
                return ResourceManager.GetString("MenuImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Workspace.
        /// </summary>
        public static string MenuLockWorkspace {
            get {
                return ResourceManager.GetString("MenuLockWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        public static string MenuNew {
            get {
                return ResourceManager.GetString("MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File....
        /// </summary>
        public static string MenuOpenFile {
            get {
                return ResourceManager.GetString("MenuOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Recent.
        /// </summary>
        public static string MenuOpenRecent {
            get {
                return ResourceManager.GetString("MenuOpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open URL....
        /// </summary>
        public static string MenuOpenUrl {
            get {
                return ResourceManager.GetString("MenuOpenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins....
        /// </summary>
        public static string MenuPlugins {
            get {
                return ResourceManager.GetString("MenuPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print....
        /// </summary>
        public static string MenuPrint {
            get {
                return ResourceManager.GetString("MenuPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string MenuSaveAs {
            get {
                return ResourceManager.GetString("MenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Copy to File....
        /// </summary>
        public static string MenuSaveCopyToFile {
            get {
                return ResourceManager.GetString("MenuSaveCopyToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to File....
        /// </summary>
        public static string MenuSaveToFile {
            get {
                return ResourceManager.GetString("MenuSaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to URL....
        /// </summary>
        public static string MenuSaveToUrl {
            get {
                return ResourceManager.GetString("MenuSaveToUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Entry&apos;s Group.
        /// </summary>
        public static string MenuSelectedEntryGroup {
            get {
                return ResourceManager.GetString("MenuSelectedEntryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string MenuShowAllEntries {
            get {
                return ResourceManager.GetString("MenuShowAllEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Entries.
        /// </summary>
        public static string MenuShowEntries {
            get {
                return ResourceManager.GetString("MenuShowEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Entries By Tag.
        /// </summary>
        public static string MenuShowEntriesByTag {
            get {
                return ResourceManager.GetString("MenuShowEntriesByTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring in 1 Day.
        /// </summary>
        public static string MenuShowEntriesExpiringIn1Day {
            get {
                return ResourceManager.GetString("MenuShowEntriesExpiringIn1Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring in 1 Week.
        /// </summary>
        public static string MenuShowEntriesExpiringIn1Week {
            get {
                return ResourceManager.GetString("MenuShowEntriesExpiringIn1Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring in 2 Days.
        /// </summary>
        public static string MenuShowEntriesExpiringIn2Days {
            get {
                return ResourceManager.GetString("MenuShowEntriesExpiringIn2Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring in 2 Weeks.
        /// </summary>
        public static string MenuShowEntriesExpiringIn2Weeks {
            get {
                return ResourceManager.GetString("MenuShowEntriesExpiringIn2Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring in 3 Days.
        /// </summary>
        public static string MenuShowEntriesExpiringIn3Days {
            get {
                return ResourceManager.GetString("MenuShowEntriesExpiringIn3Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring in 4 Weeks.
        /// </summary>
        public static string MenuShowEntriesExpiringIn4Weeks {
            get {
                return ResourceManager.GetString("MenuShowEntriesExpiringIn4Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring in 8 Weeks.
        /// </summary>
        public static string MenuShowEntriesExpiringIn8Weeks {
            get {
                return ResourceManager.GetString("MenuShowEntriesExpiringIn8Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring in the Future.
        /// </summary>
        public static string MenuShowEntriesExpiringInFuture {
            get {
                return ResourceManager.GetString("MenuShowEntriesExpiringInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string MenuShowExpiredEntries {
            get {
                return ResourceManager.GetString("MenuShowExpiredEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Entries of Subgroups.
        /// </summary>
        public static string MenuShowSubgroupEntries {
            get {
                return ResourceManager.GetString("MenuShowSubgroupEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Toolbar.
        /// </summary>
        public static string MenuShowToolbar {
            get {
                return ResourceManager.GetString("MenuShowToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By....
        /// </summary>
        public static string MenuSortBy {
            get {
                return ResourceManager.GetString("MenuSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize.
        /// </summary>
        public static string MenuSynchronize {
            get {
                return ResourceManager.GetString("MenuSynchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        public static string MenuSynchronizeRecentFiles {
            get {
                return ResourceManager.GetString("MenuSynchronizeRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize with File....
        /// </summary>
        public static string MenuSynchronizeWithFile {
            get {
                return ResourceManager.GetString("MenuSynchronizeWithFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize with URL....
        /// </summary>
        public static string MenuSynchronizeWithUrl {
            get {
                return ResourceManager.GetString("MenuSynchronizeWithUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAN View Options.
        /// </summary>
        public static string MenuTanViewOptions {
            get {
                return ResourceManager.GetString("MenuTanViewOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show TAN Indices in Entry Titles.
        /// </summary>
        public static string MenuTanViewOptionsShowTanIndicesInEntryTitles {
            get {
                return ResourceManager.GetString("MenuTanViewOptionsShowTanIndicesInEntryTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Simple List View for TAN-Only Groups.
        /// </summary>
        public static string MenuTanViewOptionsSimpleListViewTanOnlyGroups {
            get {
                return ResourceManager.GetString("MenuTanViewOptionsSimpleListViewTanOnlyGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAN Wizard....
        /// </summary>
        public static string MenuTanWizard {
            get {
                return ResourceManager.GetString("MenuTanWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers....
        /// </summary>
        public static string MenuTriggers {
            get {
                return ResourceManager.GetString("MenuTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Layout.
        /// </summary>
        public static string MenuWindowLayout {
            get {
                return ResourceManager.GetString("MenuWindowLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side by Side.
        /// </summary>
        public static string MenuWindowLayoutSideBySide {
            get {
                return ResourceManager.GetString("MenuWindowLayoutSideBySide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked.
        /// </summary>
        public static string MenuWindowLayoutStacked {
            get {
                return ResourceManager.GetString("MenuWindowLayoutStacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Replace....
        /// </summary>
        public static string MenuXmlReplace {
            get {
                return ResourceManager.GetString("MenuXmlReplace", resourceCulture);
            }
        }
    }
}
